import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import SideNav from "@/components/sidenav";
import { Toaster } from "react-hot-toast";
import SessionProvider from "@/components/SessionProvider";
import Iridescence from "@/components/reactBits/Iridescence";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "yummy",
  description: "Generated by Dennis, Konstantin, Linus",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="yummy_light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
          <Iridescence
            color={[1, 1, 1]}
            mouseReact={false}
            amplitude={0.1}
            speed={1.0}
            style={{
              position: "fixed",
              top: 0,
              left: 0,
              width: "100%",
              height: "100%",
              zIndex: -1,
            }}
          />
        <SessionProvider>
          <SideNav>{children}</SideNav>
          <Toaster position="top-right" />
        </SessionProvider>
      </body>
    </html>
  );
}
